[tool.poetry]
name = "szkolenie"
version = "0.1.0"
description = ""
authors = ["kdominikgostkowski <kdominikgostkowski@leroymerlin.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
